# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c498464dde432cb8f2c27da4fbaf14a0b050c8fd80af99aa8b98030cba9670ef0cd5f7afc7fe391a29f57f8a2f105f239ebeb75a9bf6b16027cc3bb3cc9a4892

test:
  secret_key_base: 330becfec9f4d45536be696a9417c814139670fb9ea14bd8847dc236ff52274cecc22ec5091e751ad692cb3ee659c69eb8268c0f48bb879aaa42cb93b1b0e945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
