# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27dd18f8f555af33344532b5b1a49b2498fdca2086759baa870bfd456f9d2dfc7bf635ffea3d90904439bf8f677ff47ac2ee4f2cc3e48a8477c0fa30a0a37da1

test:
  secret_key_base: 79849988868e5982581545ed276ff1fccbcdd80abb82ce5ea55487ddc467e16fa5e34474345f9a78cd4e87f47e795f4458c4fc08e73f8701499eac1049ce1760

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
