# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40487d55e497306117961ac98635c8613b424ff78f8afcfccbd2da1d896f2b6d9069684413be7f2f482c85ee9129a5cab525b11d88f05671c5c87a0cc4304fa1

test:
  secret_key_base: 3155e77180446b34bab83894079dcad5f5221b30974c388c99ff3a1d27fec8361e35442499157bda8a98bd5ad5c4e40baa5f18c3bfca7e3d38bb1aa3528d4157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
