# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 546df9ef9cff945e51d6825e9e1afb6cbb46aeda16ec3ad01ed75f550cd4432f66dafffc6bfa0f9f9ce6f0c779a987166b51a6eedc3154f3bccec8554f4941a7

test:
  secret_key_base: 83725e8eb376eda493682aaab21648216a1c7ce0c83516395d67f9ff0c4c93c40d958e3c10f45e3de2e1a6d5d5d95732f8faaca694544570657e22c14d33e853

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
